#!/bin/sh

# This is a git hook for use where the bare repos was created (Raspberry Pi).
# A nodejs server runs to server the website on our local network from the Pi.
# Static files can be reversed proxied through lighttpd/nginx. Static files 
# are the vue-cli created app/client. Nodejs acts as api server for /add ,
# /remove etc. (to maintain sqlite3 db). 
# This hook will allow dev to git push and deploy updated server/client files
# on Pi.

set -e 

PROJECT_DIR="/srv/nodejs/item_lister"
STATIC_ROOT="$PROJECT_ROOT" # TODO: this will change once reverse proxied
GIT_DIR="/srv/git/item_lister.git"
#$(mktemp -d)
# note: crontab to delete this work_tree dir weekly 
WORK_DIR="./work_tree/"

PROJECT_UPLOADS_DIR="$STATIC_ROOT/uploads"

git --git-dir="$GIT_DIR" --work-tree="$WORK_DIR" checkout -f
cd "$WORK_DIR"

cd "./client/"
npm install --save-dev
npm run build

cd "../server/"
npm install

# TODO: also update this post-update hook ( maybe first before running it? )
mv post-update "$GIT_DIR/hooks"

cp --recursive --preserve=mode,ownership  * "$STATIC_ROOT"
mkdir --parents --mode=2670 "$PROJECT_UPLOADS_DIR"
# TODO.urgent: this doesnt work without sudo!! everytime you overwrite/update the
# files the user will be pi and need sudo to change it...
# chown item_lister-nodejs_usr -R /srv/nodejs/item_lister/uploads


